export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const CREATE_JOB_BEGIN = "CREATE_JOB_BEGIN";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_ERROR = "CREATE_JOB_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const SET_EDIT_JOB = "SET_EDIT_JOB";

export const DELETE_JOB_BEGIN = 'DELETE_JOB_BEGIN';
export const DELETE_JOB_ERROR = 'DELETE_JOB_ERROR';

export const EDIT_JOB_BEGIN = "EDIT_JOB_BEGIN";
export const EDIT_JOB_SUCCESS = "EDIT_JOB_SUCCESS";
export const EDIT_JOB_ERROR = "EDIT_JOB_ERROR";

export const GET_JOBS_BEGIN = "GET_JOBS_BEGIN";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";
export const GET_JOBS_ERROR = "GET_JOBS_ERROR";

export const GET_JOBS_ON_SEARCH_BEGIN = "GET_JOBS_ON_SEARCH_BEGIN";
export const GET_JOBS_ON_SEARCH_SUCCESS = "GET_JOBS_ON_SEARCH_SUCCESS";
export const GET_JOBS_ON_SEARCH_ERROR = "GET_JOBS_ON_SEARCH_ERROR";

export const GET_USERS_ON_SEARCH_BEGIN = "GET_USERS_ON_SEARCH_BEGIN";
export const GET_USERS_ON_SEARCH_SUCCESS = "GET_USERS_ON_SEARCH_SUCCESS";
export const GET_USERS_ON_SEARCH_ERROR = "GET_USERS_ON_SEARCH_ERROR";

export const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN";
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS";
export const SHOW_STATS_ERROR = "SHOW_STATS_ERROR";

export const SHOW_MONTHLY_APPS_BEGIN = "SHOW_MONTHLY_APPS_BEGIN";
export const SHOW_MONTHLY_APPS_SUCCESS = "SHOW_MONTHLY_APPS_SUCCESS";
export const SHOW_MONTHLY_APPS_ERROR = "SHOW_MONTHLY_APPS_ERROR";

export const GET_ALL_USERS_BEGIN = "GET_ALL_USERS_BEGIN";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_ERROR = "GET_ALL_USERS_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const CHANGE_PAGE = "CHANGE_PAGE";

export const GET_CURRENT_USER_BEGIN = "GET_CURRENT_USER_BEGIN";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";

export const USERS_DATA_BEGIN = "USERS_DATA_BEGIN";
export const USERS_DATA_SUCCESS = "USERS_DATA_SUCCESS";

export const GET_USER_BEGIN = "GET_USER_BEGIN";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
